import type { Metadata } from "next";
import localFont from "next/font/local";
import { ApolloWrapper } from "@/lib/apollo-wrapper";
import { Provider } from "@/components/ui/provider";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kardoos Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>
          <ApolloWrapper>{children}</ApolloWrapper>
        </Provider>
      </body>
    </html>
  );
}
